# hydra.job.chdir: false
hydra:
  searchpath:
  # see https://hydra.cc/docs/advanced/search_path/
   - file://../cfg

headless: false

sim: ${task.sim}
env: ${task.env}

total_frames: 150_000_000
max_iters: -1
eval_interval: -1
save_interval: 10000
seed: 0

viewer:
  resolution: [960, 720]
  eye: [9, -4.5, 2.3]
  lookat: [0., 0., 1.5]

wandb:
  group: ${oc.select:..task.name}
  run_name: ${oc.select:..task.name,test}-${oc.select:..algo.name,none}
  job_type: train
  entity: mlic_academic
  project: OmniDroneTest
  mode: disabled # set to 'disabled' when debugging locally #online
  run_id:
  monitor_gym: true
  tags: 

defaults:
  - task: Hover
  - algo: mappo
  - _self_
